generated file

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3652,6 +3652,384 @@ $as_echo "no (ok)" >&6; }
     _tmp_macro_name='ads_PERL_MODULE.m4'
 
     # (required) This should be something like Foo::Bar::Baz
+    _tmp_perl_mod_name=Crypt::CBC
+    if test -z "${_tmp_perl_mod_name}"; then
+        # This is almost certainly a programmer error
+
+        { { $as_echo "$as_me:$LINENO: error:
+    ${_tmp_macro_name} ERROR: required 'PERL_MODULE_NAME' param not provided
+
+    Usage:
+        ${_tmp_macro_name}(PERL_MODULE_NAME, [REQUIRED|OPTIONAL], [PERL_MODULE_VERSION])
+" >&5
+$as_echo "$as_me: error:
+    ${_tmp_macro_name} ERROR: required 'PERL_MODULE_NAME' param not provided
+
+    Usage:
+        ${_tmp_macro_name}(PERL_MODULE_NAME, [REQUIRED|OPTIONAL], [PERL_MODULE_VERSION])
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+    fi
+
+    # (optional) If not provided, then we assume that the Perl
+    # module is required. Valid values are 'REQUIRED' or 'OPTIONAL'.
+    _tmp_perl_mod_required_or_optional=
+    if test -z "${_tmp_perl_mod_required_or_optional}"; then
+        _tmp_perl_mod_required_or_optional='REQUIRED'  # dflt
+    fi
+    if test "${_tmp_perl_mod_required_or_optional}" = 'REQUIRED' ||
+       test "${_tmp_perl_mod_required_or_optional}" = 'OPTIONAL'; then :; else
+
+        { { $as_echo "$as_me:$LINENO: error:
+    ${_tmp_macro_name} ERROR: second macro param must be either 'REQUIRED' or 'OPTIONAL' (got \"${_tmp_perl_mod_required_or_optional}\")
+
+    Usage:
+        ${_tmp_macro_name}(PERL_MODULE_NAME, [REQUIRED|OPTIONAL], [PERL_MODULE_VERSION])
+" >&5
+$as_echo "$as_me: error:
+    ${_tmp_macro_name} ERROR: second macro param must be either 'REQUIRED' or 'OPTIONAL' (got \"${_tmp_perl_mod_required_or_optional}\")
+
+    Usage:
+        ${_tmp_macro_name}(PERL_MODULE_NAME, [REQUIRED|OPTIONAL], [PERL_MODULE_VERSION])
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+    fi
+
+    # (optional) If provided, this should be the perl module version
+    _tmp_perl_mod_version=
+
+    _tmp_check_msg="for ${_tmp_perl_mod_name}"
+    if test -n "${_tmp_perl_mod_version}"; then
+        _tmp_check_msg="${_tmp_check_msg} ${_tmp_perl_mod_version}"
+    fi
+
+    _tmp_perl_mod_msg_version="${_tmp_perl_mod_version}"
+    if test -z "${_tmp_perl_mod_version}"; then
+        _tmp_perl_mod_msg_version='(any version)'
+    fi
+
+    { $as_echo "$as_me:$LINENO: checking for ${_tmp_check_msg}" >&5
+$as_echo_n "checking for ${_tmp_check_msg}... " >&6; }
+
+    # Invoking perl twice is inefficient, but better isolates our test
+
+    # Only redirect stderr to /dev/null if module is optional. This prevents
+    # Perl's error messages from cluttering up the 'configure' output with
+    # error messages that may look to the user as though something is wrong.
+    #
+    if test "${_tmp_perl_mod_required_or_optional}" = 'REQUIRED'; then
+        eval "'""${PERL}""'" "${ax_perl5_extra_includes_opt}" \
+                  -we "'""use strict; use ${_tmp_perl_mod_name} ${_tmp_perl_mod_version};""'"
+    else
+
+        eval "'""${PERL}""'" "${ax_perl5_extra_includes_opt}" \
+                  -we "'""use strict; use ${_tmp_perl_mod_name} ${_tmp_perl_mod_version};""'" 2>/dev/null
+    fi
+    if test $? -eq 0; then
+        # Great, we have the module. Now print where it was found:
+        _tmp_perl_mod_path="$( eval "'""${PERL}""'" "${ax_perl5_extra_includes_opt}" \
+          -MFile::Spec -wle "'"'
+            use strict;
+            my $modname = shift;
+            eval "require ${modname}";
+            ${@} and die qq{Was unable to require module "$modname": ${@}};
+            $modname .= q{.pm};
+            my $found = undef;
+            my $shortpath = File::Spec->catdir( split(q{::}, $modname) );
+            my $fullpath;
+            if (exists $INC{ $shortpath } && defined $INC{ $shortpath }) {
+                $found = 1;
+                $fullpath = $INC{ $shortpath };
+            }
+            $fullpath = q{<path unavailable in %INC}
+                unless defined $fullpath && length $fullpath;
+            print $fullpath;
+            exit ($found ? 0 : 1);  # parens required
+        '"'" "'""${_tmp_perl_mod_name}""'")"
+        if test $? -ne 0; then
+
+
+
+            { { $as_echo "$as_me:$LINENO: error:
+    Perl module ${_tmp_perl_mod_name} exists, but 'configure' was unable to
+    determine the path to the module. This is likely a bug in the ${_tmp_macro_name}
+    autoconf macro; please report this as a bug.
+" >&5
+$as_echo "$as_me: error:
+    Perl module ${_tmp_perl_mod_name} exists, but 'configure' was unable to
+    determine the path to the module. This is likely a bug in the ${_tmp_macro_name}
+    autoconf macro; please report this as a bug.
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+        fi
+
+        # Always attempt to determine the version number of the module
+        # that was acutally found and display it to the user. Not all
+        # Perl modules provide a $VERSION variable, but if the one
+        # we're testing for does, then we'll show it.
+        #
+        # Note that we do this even for those modules for which the
+        # user has requested a specific version because the
+        # user-specified version is understood as "this version or
+        # newer", so may be different from the version of the module
+        # actually found on the system.
+
+        _tmp_found_mod_version="$(
+          eval "'""${PERL}""'" "'""-M${_tmp_perl_mod_name}""'" \
+            "${ax_perl5_extra_includes_opt}" -wle "'"'
+               my $modname = shift;
+               my $ver = "${modname}::VERSION";
+               print $$ver if defined $$ver && length $$ver;
+            '"'" "'""${_tmp_perl_mod_name}""'"
+        )"
+        if test $? -ne 0; then
+
+                { { $as_echo "$as_me:$LINENO: error:
+    Perl module ${_tmp_perl_mod_name} exists, but 'configure' was unable to
+    test whether or not the module specifies a version number. This is likely
+    a bug in the ${_tmp_macro_name} autoconf macro; please report this as a bug.
+" >&5
+$as_echo "$as_me: error:
+    Perl module ${_tmp_perl_mod_name} exists, but 'configure' was unable to
+    test whether or not the module specifies a version number. This is likely
+    a bug in the ${_tmp_macro_name} autoconf macro; please report this as a bug.
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+        fi
+
+        if test "${_tmp_found_mod_version}x" = 'x'; then
+            # Module does not provide version info, so use bogon string
+            _tmp_perl_mod_path="(???) ${_tmp_perl_mod_path}"
+        else
+            # Prepend the value to the module path for display to the user
+            _tmp_perl_mod_path="(${_tmp_found_mod_version}) ${_tmp_perl_mod_path}"
+        fi
+
+        { $as_echo "$as_me:$LINENO: result: ${_tmp_perl_mod_path}" >&5
+$as_echo "${_tmp_perl_mod_path}" >&6; }
+
+    else
+        if test "${_tmp_perl_mod_required_or_optional}" = 'REQUIRED'; then
+
+            { { $as_echo "$as_me:$LINENO: error:
+    Was unable to locate Perl module ${_tmp_perl_mod_name} ${_tmp_perl_mod_msg_version}
+" >&5
+$as_echo "$as_me: error:
+    Was unable to locate Perl module ${_tmp_perl_mod_name} ${_tmp_perl_mod_msg_version}
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+        else  # presence of module was optional
+
+            { $as_echo "$as_me:$LINENO: result: no (ok)" >&5
+$as_echo "no (ok)" >&6; }
+
+        fi
+    fi
+
+
+
+
+
+
+
+
+    _tmp_macro_name='ads_PERL_MODULE.m4'
+
+    # (required) This should be something like Foo::Bar::Baz
+    _tmp_perl_mod_name=Crypt::DES
+    if test -z "${_tmp_perl_mod_name}"; then
+        # This is almost certainly a programmer error
+
+        { { $as_echo "$as_me:$LINENO: error:
+    ${_tmp_macro_name} ERROR: required 'PERL_MODULE_NAME' param not provided
+
+    Usage:
+        ${_tmp_macro_name}(PERL_MODULE_NAME, [REQUIRED|OPTIONAL], [PERL_MODULE_VERSION])
+" >&5
+$as_echo "$as_me: error:
+    ${_tmp_macro_name} ERROR: required 'PERL_MODULE_NAME' param not provided
+
+    Usage:
+        ${_tmp_macro_name}(PERL_MODULE_NAME, [REQUIRED|OPTIONAL], [PERL_MODULE_VERSION])
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+    fi
+
+    # (optional) If not provided, then we assume that the Perl
+    # module is required. Valid values are 'REQUIRED' or 'OPTIONAL'.
+    _tmp_perl_mod_required_or_optional=
+    if test -z "${_tmp_perl_mod_required_or_optional}"; then
+        _tmp_perl_mod_required_or_optional='REQUIRED'  # dflt
+    fi
+    if test "${_tmp_perl_mod_required_or_optional}" = 'REQUIRED' ||
+       test "${_tmp_perl_mod_required_or_optional}" = 'OPTIONAL'; then :; else
+
+        { { $as_echo "$as_me:$LINENO: error:
+    ${_tmp_macro_name} ERROR: second macro param must be either 'REQUIRED' or 'OPTIONAL' (got \"${_tmp_perl_mod_required_or_optional}\")
+
+    Usage:
+        ${_tmp_macro_name}(PERL_MODULE_NAME, [REQUIRED|OPTIONAL], [PERL_MODULE_VERSION])
+" >&5
+$as_echo "$as_me: error:
+    ${_tmp_macro_name} ERROR: second macro param must be either 'REQUIRED' or 'OPTIONAL' (got \"${_tmp_perl_mod_required_or_optional}\")
+
+    Usage:
+        ${_tmp_macro_name}(PERL_MODULE_NAME, [REQUIRED|OPTIONAL], [PERL_MODULE_VERSION])
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+    fi
+
+    # (optional) If provided, this should be the perl module version
+    _tmp_perl_mod_version=
+
+    _tmp_check_msg="for ${_tmp_perl_mod_name}"
+    if test -n "${_tmp_perl_mod_version}"; then
+        _tmp_check_msg="${_tmp_check_msg} ${_tmp_perl_mod_version}"
+    fi
+
+    _tmp_perl_mod_msg_version="${_tmp_perl_mod_version}"
+    if test -z "${_tmp_perl_mod_version}"; then
+        _tmp_perl_mod_msg_version='(any version)'
+    fi
+
+    { $as_echo "$as_me:$LINENO: checking for ${_tmp_check_msg}" >&5
+$as_echo_n "checking for ${_tmp_check_msg}... " >&6; }
+
+    # Invoking perl twice is inefficient, but better isolates our test
+
+    # Only redirect stderr to /dev/null if module is optional. This prevents
+    # Perl's error messages from cluttering up the 'configure' output with
+    # error messages that may look to the user as though something is wrong.
+    #
+    if test "${_tmp_perl_mod_required_or_optional}" = 'REQUIRED'; then
+        eval "'""${PERL}""'" "${ax_perl5_extra_includes_opt}" \
+                  -we "'""use strict; use ${_tmp_perl_mod_name} ${_tmp_perl_mod_version};""'"
+    else
+
+        eval "'""${PERL}""'" "${ax_perl5_extra_includes_opt}" \
+                  -we "'""use strict; use ${_tmp_perl_mod_name} ${_tmp_perl_mod_version};""'" 2>/dev/null
+    fi
+    if test $? -eq 0; then
+        # Great, we have the module. Now print where it was found:
+        _tmp_perl_mod_path="$( eval "'""${PERL}""'" "${ax_perl5_extra_includes_opt}" \
+          -MFile::Spec -wle "'"'
+            use strict;
+            my $modname = shift;
+            eval "require ${modname}";
+            ${@} and die qq{Was unable to require module "$modname": ${@}};
+            $modname .= q{.pm};
+            my $found = undef;
+            my $shortpath = File::Spec->catdir( split(q{::}, $modname) );
+            my $fullpath;
+            if (exists $INC{ $shortpath } && defined $INC{ $shortpath }) {
+                $found = 1;
+                $fullpath = $INC{ $shortpath };
+            }
+            $fullpath = q{<path unavailable in %INC}
+                unless defined $fullpath && length $fullpath;
+            print $fullpath;
+            exit ($found ? 0 : 1);  # parens required
+        '"'" "'""${_tmp_perl_mod_name}""'")"
+        if test $? -ne 0; then
+
+
+
+            { { $as_echo "$as_me:$LINENO: error:
+    Perl module ${_tmp_perl_mod_name} exists, but 'configure' was unable to
+    determine the path to the module. This is likely a bug in the ${_tmp_macro_name}
+    autoconf macro; please report this as a bug.
+" >&5
+$as_echo "$as_me: error:
+    Perl module ${_tmp_perl_mod_name} exists, but 'configure' was unable to
+    determine the path to the module. This is likely a bug in the ${_tmp_macro_name}
+    autoconf macro; please report this as a bug.
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+        fi
+
+        # Always attempt to determine the version number of the module
+        # that was acutally found and display it to the user. Not all
+        # Perl modules provide a $VERSION variable, but if the one
+        # we're testing for does, then we'll show it.
+        #
+        # Note that we do this even for those modules for which the
+        # user has requested a specific version because the
+        # user-specified version is understood as "this version or
+        # newer", so may be different from the version of the module
+        # actually found on the system.
+
+        _tmp_found_mod_version="$(
+          eval "'""${PERL}""'" "'""-M${_tmp_perl_mod_name}""'" \
+            "${ax_perl5_extra_includes_opt}" -wle "'"'
+               my $modname = shift;
+               my $ver = "${modname}::VERSION";
+               print $$ver if defined $$ver && length $$ver;
+            '"'" "'""${_tmp_perl_mod_name}""'"
+        )"
+        if test $? -ne 0; then
+
+                { { $as_echo "$as_me:$LINENO: error:
+    Perl module ${_tmp_perl_mod_name} exists, but 'configure' was unable to
+    test whether or not the module specifies a version number. This is likely
+    a bug in the ${_tmp_macro_name} autoconf macro; please report this as a bug.
+" >&5
+$as_echo "$as_me: error:
+    Perl module ${_tmp_perl_mod_name} exists, but 'configure' was unable to
+    test whether or not the module specifies a version number. This is likely
+    a bug in the ${_tmp_macro_name} autoconf macro; please report this as a bug.
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+        fi
+
+        if test "${_tmp_found_mod_version}x" = 'x'; then
+            # Module does not provide version info, so use bogon string
+            _tmp_perl_mod_path="(???) ${_tmp_perl_mod_path}"
+        else
+            # Prepend the value to the module path for display to the user
+            _tmp_perl_mod_path="(${_tmp_found_mod_version}) ${_tmp_perl_mod_path}"
+        fi
+
+        { $as_echo "$as_me:$LINENO: result: ${_tmp_perl_mod_path}" >&5
+$as_echo "${_tmp_perl_mod_path}" >&6; }
+
+    else
+        if test "${_tmp_perl_mod_required_or_optional}" = 'REQUIRED'; then
+
+            { { $as_echo "$as_me:$LINENO: error:
+    Was unable to locate Perl module ${_tmp_perl_mod_name} ${_tmp_perl_mod_msg_version}
+" >&5
+$as_echo "$as_me: error:
+    Was unable to locate Perl module ${_tmp_perl_mod_name} ${_tmp_perl_mod_msg_version}
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+        else  # presence of module was optional
+
+            { $as_echo "$as_me:$LINENO: result: no (ok)" >&5
+$as_echo "no (ok)" >&6; }
+
+        fi
+    fi
+
+
+
+
+
+
+
+
+    _tmp_macro_name='ads_PERL_MODULE.m4'
+
+    # (required) This should be something like Foo::Bar::Baz
     _tmp_perl_mod_name=CGI
     if test -z "${_tmp_perl_mod_name}"; then
         # This is almost certainly a programmer error
