3.8.1 - <iif> refactor, enhanced test framework, minor bug fixes

diff --git a/src/main/perl/run-tests b/src/main/perl/run-tests
--- a/src/main/perl/run-tests
+++ b/src/main/perl/run-tests
@@ -14,8 +14,11 @@ cleanup() {
 }
 
 ########################################################################
-# main script starts here
+# MAIN SCRIPT STARTS HERE
 ########################################################################
+
+set -oue pipefail
+trap cleanup EXIT
 
 # run Bedrock tag tests
 TESTS="$(cat $1)"
@@ -27,11 +30,13 @@ mkdir $test_dir/t
 
 for a in $TESTS; do 
     test_file=$(basename $a .yml)
-    ln -s $SRC/test-tag.pl ${test_dir}/t/${test_file}.t
+    ln -s $SRC/t/$(basename $a) ${test_dir}/t/${test_file}.yml
+    ln -s $SRC/bin/bedrock-runner.pl ${test_dir}/t/${test_file}.t
     test -e $test_dir/t/$test_file.t || exit 1;
 done
 
-SOCKET_PATH=/tmp/mysqld/mysqld.sock
+SOCKET_PATH="${SOCKET_PATH:-/tmp/mysqld/mysqld.sock}"
+DBI_SOCKET="${DBI_SOCKET:-}"
 
 if test -z "$DBI_SOCKET"; then
     if test -e "$SOCKET_PATH"; then 
@@ -39,13 +44,13 @@ if test -z "$DBI_SOCKET"; then
     fi
 fi
 
-CONFIG_PATH="$SRC/t/config:.:$BUILD/../bedrock/config"
-TEST_PATH="$SRC"
-PROVE=$(command -v prove)
+PROVE="$(command -v prove)"
+if test -z "$PROVE"; then
+    echo "ERROR: could not find 'prove'"
+    exit 1
+fi
 
-CONFIG_PATH=$CONFIG_PATH \
+BEDROCK_CONFIG_PATH="$SRC/t/config" \
 $PROVE -v -I "$BUILD/lib" -I "$BUILD/lib/Bedrock" -I "$BUILD/lib/Bedrock/Text" "$test_dir/t"
-
-cleanup
 
 exit 0
